services:
  - name: frontend
    image: okteto/angular:latest
    command: ["ng", "serve", "--host", "0.0.0.0"]
    securityContext:
      capabilities:
        add: ["NET_BIND_SERVICE"]
    ports:
      - 4200:4200
    working_dir: /app/client
    volumes:
      - ./client:/app/client

  - name: backend
    build: .
    command: ["npm", "run", "start:dev"]
    securityContext:
      capabilities:
        add: ["NET_BIND_SERVICE"]
    ports:
      - 3000:3000
    working_dir: /app/api
    volumes:
      - ./api:/app/api
