export const cities = [
  'abejorral',
  'abrego',
  'abriaquí',
  'acacías',
  'acandí',
  'acevedo',
  'achí',
  'agrado',
  'agua de dios',
  'aguachica',
  'aguada',
  'aguadas',
  'aguazul',
  'agustín codazzi',
  'aipe',
  'albán',
  'albania',
  'alcalá',
  'aldana',
  'alejandría',
  'algarrobo',
  'algeciras',
  'almaguer',
  'almeida',
  'alpujarra',
  'altamira',
  'alto baudo',
  'altos del rosario',
  'alvarado',
  'amagá',
  'amalfi',
  'ambalema',
  'anapoima',
  'ancuyá',
  'andalucía',
  'andes',
  'angelópolis',
  'angostura',
  'anolaima',
  'anorí',
  'anserma',
  'ansermanuevo',
  'anza',
  'anzoátegui',
  'apartadó',
  'apía',
  'apulo',
  'aquitania',
  'aracataca',
  'aranzazu',
  'aratoca',
  'arauca',
  'arauquita',
  'arbeláez',
  'arboleda',
  'arboledas',
  'arboletes',
  'arcabuco',
  'arenal',
  'argelia',
  'ariguaní',
  'arjona',
  'armenia',
  'armero',
  'arroyohondo',
  'astrea',
  'ataco',
  'atrato',
  'ayapel',
  'bagadó',
  'bahía solano',
  'bajo baudó',
  'balboa',
  'baranoa',
  'baraya',
  'barbacoas',
  'barbosa',
  'barichara',
  'barranca de upía',
  'barrancabermeja',
  'barrancas',
  'barranco de loba',
  'barranco minas',
  'barranquilla',
  'becerril',
  'belalcázar',
  'belén',
  'belén de bajirá',
  'bello',
  'belmira',
  'beltrán',
  'berbeo',
  'betania',
  'betéitiva',
  'betulia',
  'bituima',
  'boavita',
  'bochalema',
  'bogotá',
  'bojacá',
  'bojaya',
  'bolívar',
  'bosconia',
  'boyacá',
  'briceño',
  'bucaramanga',
  'bucarasica',
  'buenaventura',
  'buenavista',
  'buenos aires',
  'buesaco',
  'buga',
  'bugalagrande',
  'buriticá',
  'busbanzá',
  'cabrera',
  'cabuyaro',
  'cacahual',
  'cáceres',
  'cachipay',
  'cachirá',
  'cácota',
  'caicedo',
  'caicedonia',
  'caimito',
  'cajamarca',
  'cajibío',
  'cajicá',
  'calamar',
  'calarca',
  'caldas',
  'caldono',
  'cali',
  'california',
  'calima',
  'caloto',
  'campamento',
  'campo de la cruz',
  'campoalegre',
  'campohermoso',
  'canalete',
  'cañasgordas',
  'candelaria',
  'cantagallo',
  'caparrapí',
  'capitanejo',
  'caqueza',
  'caracolí',
  'caramanta',
  'carcasí',
  'carepa',
  'carmen de apicalá',
  'carmen de carupa',
  'carmen del darien',
  'carolina',
  'cartagena',
  'cartagena del chairá',
  'cartago',
  'caruru',
  'casabianca',
  'castilla la nueva',
  'caucasia',
  'cepitá',
  'cereté',
  'cerinza',
  'cerrito',
  'cerro san antonio',
  'cértegui',
  'chachagüí',
  'chaguaní',
  'chalán',
  'chameza',
  'chaparral',
  'charalá',
  'charta',
  'chía',
  'chibolo',
  'chigorodó',
  'chima',
  'chimá',
  'chimichagua',
  'chinácota',
  'chinavita',
  'chinchiná',
  'chinú',
  'chipaque',
  'chipatá',
  'chiquinquirá',
  'chíquiza',
  'chiriguaná',
  'chiscas',
  'chita',
  'chitagá',
  'chitaraque',
  'chivatá',
  'chivor',
  'choachí',
  'chocontá',
  'cicuco',
  'ciénaga',
  'ciénaga de oro',
  'ciénega',
  'cimitarra',
  'circasia',
  'cisneros',
  'ciudad bolívar',
  'clemencia',
  'cocorná',
  'coello',
  'cogua',
  'colombia',
  'colón',
  'coloso',
  'cómbita',
  'concepción',
  'concordia',
  'condoto',
  'confines',
  'consaca',
  'contadero',
  'contratación',
  'convención',
  'copacabana',
  'coper',
  'córdoba',
  'corinto',
  'coromoro',
  'corozal',
  'corrales',
  'cota',
  'cotorra',
  'covarachía',
  'coveñas',
  'coyaima',
  'cravo norte',
  'cuaspud',
  'cubará',
  'cubarral',
  'cucaita',
  'cucunubá',
  'cúcuta',
  'cucutilla',
  'cuítiva',
  'cumaral',
  'cumaribo',
  'cumbal',
  'cumbitara',
  'cunday',
  'curillo',
  'curití',
  'curumaní',
  'dabeiba',
  'dagua',
  'dibulla',
  'distracción',
  'dolores',
  'don matías',
  'dosquebradas',
  'duitama',
  'durania',
  'ebéjico',
  'el águila',
  'el bagre',
  'el banco',
  'el cairo',
  'el calvario',
  'el carmen',
  'el carmen de atrato',
  'el carmen de bolívar',
  'el carmen de chucurí',
  'el carmen de viboral',
  'el castillo',
  'el cerrito',
  'el charco',
  'el cocuy',
  'el colegio',
  'el copey',
  'el doncello',
  'el dorado',
  'el dovio',
  'el encanto',
  'el espino',
  'el guacamayo',
  'el guamo',
  'el molino',
  'el paso',
  'el paujil',
  'el peñol',
  'el peñón',
  'el piñon',
  'el playón',
  'el retén',
  'el retorno',
  'el roble',
  'el rosal',
  'el rosario',
  'el santuario',
  'el tablón de gómez',
  'el tambo',
  'el tarra',
  'el zulia',
  'elías',
  'encino',
  'enciso',
  'entrerrios',
  'envigado',
  'espinal',
  'facatativá',
  'falan',
  'filadelfia',
  'filandia',
  'firavitoba',
  'flandes',
  'florencia',
  'floresta',
  'florián',
  'florida',
  'floridablanca',
  'fomeque',
  'fonseca',
  'fortul',
  'fosca',
  'francisco pizarro',
  'fredonia',
  'fresno',
  'frontino',
  'fuente de oro',
  'fundación',
  'funes',
  'funza',
  'fúquene',
  'fusagasugá',
  'gachala',
  'gachancipá',
  'gachantivá',
  'gachetá',
  'galán',
  'galapa',
  'galeras',
  'gama',
  'gamarra',
  'gambita',
  'gameza',
  'garagoa',
  'garzón',
  'génova',
  'gigante',
  'ginebra',
  'giraldo',
  'girardot',
  'girardota',
  'girón',
  'gómez plata',
  'gonzález',
  'gramalote',
  'granada',
  'guaca',
  'guacamayas',
  'guacarí',
  'guachetá',
  'guachucal',
  'guadalupe',
  'guaduas',
  'guaitarilla',
  'gualmatán',
  'guamal',
  'guamo',
  'guapi',
  'guapotá',
  'guaranda',
  'guarne',
  'guasca',
  'guatape',
  'guataquí',
  'guatavita',
  'guateque',
  'guática',
  'guavatá',
  'guayabal de siquima',
  'guayabetal',
  'guayatá',
  'güepsa',
  'güicán',
  'gutiérrez',
  'hacarí',
  'hatillo de loba',
  'hato',
  'hato corozal',
  'hatonuevo',
  'heliconia',
  'herrán',
  'herveo',
  'hispania',
  'hobo',
  'honda',
  'ibagué',
  'icononzo',
  'iles',
  'imués',
  'inírida',
  'inzá',
  'ipiales',
  'iquira',
  'isnos',
  'istmina',
  'itagui',
  'ituango',
  'iza',
  'jambaló',
  'jamundí',
  'jardín',
  'jenesano',
  'jericó',
  'jerusalén',
  'jesús maría',
  'jordán',
  'juan de acosta',
  'junín',
  'juradó',
  'la apartada',
  'la argentina',
  'la belleza',
  'la calera',
  'la capilla',
  'la ceja',
  'la celia',
  'la chorrera',
  'la cruz',
  'la cumbre',
  'la dorada',
  'la esperanza',
  'la estrella',
  'la florida',
  'la gloria',
  'la guadalupe',
  'la jagua de ibirico',
  'la jagua del pilar',
  'la llanada',
  'la macarena',
  'la merced',
  'la mesa',
  'la montañita',
  'la palma',
  'la paz',
  'la pedrera',
  'la peña',
  'la pintada',
  'la plata',
  'la playa',
  'la primavera',
  'la salina',
  'la sierra',
  'la tebaida',
  'la tola',
  'la unión',
  'la uvita',
  'la vega',
  'la victoria',
  'la victoria',
  'la virginia',
  'labateca',
  'labranzagrande',
  'landázuri',
  'lebríja',
  'leguízamo',
  'leiva',
  'lejanías',
  'lenguazaque',
  'lérida',
  'leticia',
  'líbano',
  'liborina',
  'linares',
  'lloró',
  'lópez',
  'lorica',
  'los andes',
  'los córdobas',
  'los palmitos',
  'los patios',
  'los santos',
  'lourdes',
  'luruaco',
  'macanal',
  'macaravita',
  'maceo',
  'macheta',
  'madrid',
  'magangué',
  'magüi',
  'mahates',
  'maicao',
  'majagual',
  'málaga',
  'malambo',
  'mallama',
  'manatí',
  'manaure',
  'maní',
  'manizales',
  'manta',
  'manzanares',
  'mapiripán',
  'mapiripana',
  'margarita',
  'maría la baja',
  'marinilla',
  'maripí',
  'mariquita',
  'marmato',
  'marquetalia',
  'marsella',
  'marulanda',
  'matanza',
  'medellín',
  'medina',
  'medio atrato',
  'medio baudó',
  'medio san juan',
  'melgar',
  'mercaderes',
  'mesetas',
  'milán',
  'miraflores',
  'miranda',
  'miriti paraná',
  'mistrató',
  'mitú',
  'mocoa',
  'mogotes',
  'molagavita',
  'momil',
  'mompós',
  'mongua',
  'monguí',
  'moniquirá',
  'moñitos',
  'montebello',
  'montecristo',
  'montelíbano',
  'montenegro',
  'montería',
  'monterrey',
  'morales',
  'morelia',
  'morichal',
  'morroa',
  'mosquera',
  'motavita',
  'murillo',
  'murindó',
  'mutatá',
  'mutiscua',
  'muzo',
  'nariño',
  'nátaga',
  'natagaima',
  'nechí',
  'necoclí',
  'neira',
  'neiva',
  'nemocón',
  'nilo',
  'nimaima',
  'nobsa',
  'nocaima',
  'norcasia',
  'nóvita',
  'nueva granada',
  'nuevo colón',
  'nunchía',
  'nuquí',
  'obando',
  'ocamonte',
  'ocaña',
  'oiba',
  'oicatá',
  'olaya',
  'olaya herrera',
  'onzaga',
  'oporapa',
  'orito',
  'orocué',
  'ortega',
  'ospina',
  'otanche',
  'ovejas',
  'pachavita',
  'pacho',
  'pacoa',
  'pácora',
  'padilla',
  'paez',
  'páez',
  'paicol',
  'pailitas',
  'paime',
  'paipa',
  'pajarito',
  'palermo',
  'palestina',
  'palmar',
  'palmar de varela',
  'palmas del socorro',
  'palmira',
  'palmito',
  'palocabildo',
  'pamplona',
  'pamplonita',
  'pana pana',
  'pandi',
  'panqueba',
  'papunaua',
  'páramo',
  'paratebueno',
  'pasca',
  'pasto',
  'patía',
  'pauna',
  'paya',
  'paz de ariporo',
  'paz de río',
  'pedraza',
  'pelaya',
  'peñol',
  'pensilvania',
  'peque',
  'pereira',
  'pesca',
  'piamonte',
  'piedecuesta',
  'piedras',
  'piendamó',
  'pijao',
  'pijiño del carmen',
  'pinchote',
  'pinillos',
  'piojó',
  'pisba',
  'pital',
  'pitalito',
  'pivijay',
  'planadas',
  'planeta rica',
  'plato',
  'policarpa',
  'polonuevo',
  'ponedera',
  'popayán',
  'pore',
  'potosí',
  'pradera',
  'prado',
  'providencia',
  'pueblo bello',
  'pueblo nuevo',
  'pueblo rico',
  'pueblorrico',
  'puebloviejo',
  'puente nacional',
  'puerres',
  'puerto alegría',
  'puerto arica',
  'puerto asís',
  'puerto berrío',
  'puerto boyacá',
  'puerto caicedo',
  'puerto carreño',
  'puerto colombia',
  'puerto concordia',
  'puerto escondido',
  'puerto gaitán',
  'puerto guzmán',
  'puerto libertador',
  'puerto lleras',
  'puerto lópez',
  'puerto nare',
  'puerto nariño',
  'puerto parra',
  'puerto rico',
  'puerto rondón',
  'puerto salgar',
  'puerto santander',
  'puerto tejada',
  'puerto triunfo',
  'puerto wilches',
  'pulí',
  'pupiales',
  'puracé',
  'purificación',
  'purísima',
  'quebradanegra',
  'quetame',
  'quibdó',
  'quimbaya',
  'quinchía',
  'quípama',
  'quipile',
  'ragonvalia',
  'ramiriquí',
  'ráquira',
  'recetor',
  'regidor',
  'remedios',
  'remolino',
  'repelón',
  'restrepo',
  'retiro',
  'ricaurte',
  'río de oro',
  'río iro',
  'río quito',
  'río viejo',
  'rioblanco',
  'riofrío',
  'riohacha',
  'rionegro',
  'riosucio',
  'risaralda',
  'rivera',
  'roberto payán',
  'roldanillo',
  'roncesvalles',
  'rondón',
  'rosas',
  'rovira',
  'sabana de torres',
  'sabanagrande',
  'sabanalarga',
  'sabanas de san angel',
  'sabaneta',
  'saboyá',
  'sácama',
  'sáchica',
  'sahagún',
  'saladoblanco',
  'salamina',
  'salazar',
  'saldaña',
  'salento',
  'salgar',
  'samacá',
  'samaná',
  'samaniego',
  'sampués',
  'san agustín',
  'san alberto',
  'san andrés',
  'san andrés sotavento',
  'san antero',
  'san antonio',
  'san benito',
  'san benito abad',
  'san bernardo',
  'san calixto',
  'san carlos',
  'san carlos de guaroa',
  'san cayetano',
  'san cristóbal',
  'san diego',
  'san eduardo',
  'san estanislao',
  'san felipe',
  'san fernando',
  'san francisco',
  'san gil',
  'san jacinto',
  'san jacinto del cauca',
  'san jerónimo',
  'san joaquín',
  'san josé',
  'san josé de miranda',
  'san josé de pare',
  'san josé del fragua',
  'san josé del guaviare',
  'san josé del palmar',
  'san juan de arama',
  'san juan de betulia',
  'san juan de río seco',
  'san juan de urabá',
  'san juan del cesar',
  'san juan nepomuceno',
  'san juanito',
  'san lorenzo',
  'san luis',
  'san luis de gaceno',
  'san luis de palenque',
  'san marcos',
  'san martín',
  'san martín de loba',
  'san mateo',
  'san miguel',
  'san miguel de sema',
  'san onofre',
  'san pablo',
  'san pablo de borbur',
  'san pedro',
  'san pedro de cartago',
  'san pedro de uraba',
  'san pelayo',
  'san rafael',
  'san roque',
  'san sebastián',
  'san vicente',
  'san zenón',
  'sandoná',
  'santa ana',
  'santa bárbara',
  'santa catalina',
  'santa helena del opón',
  'santa isabel',
  'santa lucía',
  'santa maría',
  'santa marta',
  'santa rosa',
  'santa rosa de cabal',
  'santa rosa de osos',
  'santa rosa de viterbo',
  'santa rosa del sur',
  'santa rosalía',
  'santa sofía',
  'santacruz',
  'santafé de antioquia',
  'santana',
  'santiago',
  'santiago de tolú',
  'santo domingo',
  'santo tomás',
  'santuario',
  'sapuyes',
  'saravena',
  'sardinata',
  'sasaima',
  'sativanorte',
  'sativasur',
  'segovia',
  'sesquilé',
  'sevilla',
  'siachoque',
  'sibaté',
  'sibundoy',
  'silos',
  'silvania',
  'silvia',
  'simacota',
  'simijaca',
  'simití',
  'sincé',
  'sincelejo',
  'sipí',
  'sitionuevo',
  'soacha',
  'soatá',
  'socha',
  'socorro',
  'socotá',
  'sogamoso',
  'solano',
  'soledad',
  'solita',
  'somondoco',
  'sonson',
  'sopetrán',
  'soplaviento',
  'sopó',
  'sora',
  'soracá',
  'sotaquirá',
  'sotara',
  'suaita',
  'suan',
  'suárez',
  'suaza',
  'subachoque',
  'sucre',
  'suesca',
  'supatá',
  'supía',
  'suratá',
  'susa',
  'susacón',
  'sutamarchán',
  'sutatausa',
  'sutatenza',
  'tabio',
  'tadó',
  'talaigua nuevo',
  'tamalameque',
  'támara',
  'tame',
  'támesis',
  'taminango',
  'tangua',
  'taraira',
  'tarapacá',
  'tarazá',
  'tarqui',
  'tarso',
  'tasco',
  'tauramena',
  'tausa',
  'tello',
  'tena',
  'tenerife',
  'tenjo',
  'tenza',
  'teorama',
  'teruel',
  'tesalia',
  'tibacuy',
  'tibaná',
  'tibasosa',
  'tibirita',
  'tibú',
  'tierralta',
  'timaná',
  'timbío',
  'timbiquí',
  'tinjacá',
  'tipacoque',
  'tiquisio',
  'titiribí',
  'toca',
  'tocaima',
  'tocancipá',
  'togüí',
  'toledo',
  'tolú viejo',
  'tona',
  'tópaga',
  'topaipí',
  'toribio',
  'toro',
  'tota',
  'totoró',
  'trinidad',
  'trujillo',
  'tubará',
  'tuluá',
  'tumaco',
  'tunja',
  'tununguá',
  'túquerres',
  'turbaco',
  'turbaná',
  'turbo',
  'turmequé',
  'tuta',
  'tutazá',
  'ubalá',
  'ubaque',
  'ulloa',
  'umbita',
  'une',
  'unguía',
  'unión panamericana',
  'uramita',
  'uribe',
  'uribia',
  'urrao',
  'urumita',
  'usiacurí',
  'útica',
  'valdivia',
  'valencia',
  'valle de san josé',
  'valle de san juan',
  'valle del guamuez',
  'valledupar',
  'valparaíso',
  'vegachí',
  'vélez',
  'venadillo',
  'venecia',
  'ventaquemada',
  'vergara',
  'versalles',
  'vetas',
  'vianí',
  'victoria',
  'vigía del fuerte',
  'vijes',
  'villa caro',
  'villa de leyva',
  'villa del rosario',
  'villa rica',
  'villagarzón',
  'villagómez',
  'villahermosa',
  'villamaría',
  'villanueva',
  'villapinzón',
  'villarrica',
  'villavicencio',
  'villavieja',
  'villeta',
  'viotá',
  'viracachá',
  'vistahermosa',
  'viterbo',
  'yacopí',
  'yacuanquer',
  'yaguará',
  'yalí',
  'yarumal',
  'yavaraté',
  'yolombó',
  'yondó',
  'yopal',
  'yotoco',
  'yumbo',
  'zambrano',
  'zapatoca',
  'zapayán',
  'zaragoza',
  'zarzal',
  'zetaquira',
  'zipacón',
  'zipaquirá',
  'zona bananera',
];

export type City = (typeof cities)[number];
